#!/bin/bash

EC_WS=0.00001
CC_WS=0.00001

rm *_initial.struct

echo "
File *_initial.struct has been removed." >> STDOUT_opt


printf '1\n4\n-5\n-2.5\n2.5\n5' | x optimize >> STDOUT_step_xopt

sed -i -e "s/ run_lapw -ec 0.0001   #/run_lapw -ec $EC_WS -cc $CC_WS -p   #/g" optimize.job
sed -i -e "s/_default/ /g" optimize.job

echo "Optimization points calculations prepared." >> STDOUT_opt

#echo ''|./optimize.job >STDOUT 2>$1

TIME=`date +%F-%T.%N`

echo "Optimization points have been calculated.
Finish time: $TIME
" >> STDOUT_opt
