#!/bin/bash
CASE=$1

VOL0=$(awk 'FNR == 23 {print $2}' $CASE.outputeos | bc)
VOL1=$(awk 'FNR == 28 {print $1}' $CASE.outputeos | bc)
A1=$(awk 'FNR == 4 {print $1}' $CASE.struct | bc)

A0=$(python -c "print(round($A1*($VOL0/$VOL1)**(1./3),6))")

echo "
Changing cell parameters: a (cubic)
" >> STDOUT_opt
echo "Volume: $VOL1 --> $VOL0" >> STDOUT_opt
echo "a: $A1 --> $A0" >> STDOUT_opt

sed -i -e "s/$A1/$A0/g" $CASE.struct

TIME=`date +%F-%T.%N`

echo "
STRUCT file has been modified.
Finish time: $TIME
" >> STDOUT_opt