#!/bin/bash

echo "
========================
Running eos_run ...
========================
" >> STDOUT_opt


if [ -e $CASE_WS\_initial.struct ]
	then
	rm $CASE_WS\_initial.struct
fi


echo "File *_initial.struct has been removed." >> STDOUT_opt

printf '1\n4\n-5\n-2.5\n2.5\n5\n' | x optimize #>> STDOUT_opt #2>&1

if [ $? -eq 1 ]
	then
	echo "!!! Error in x optimize !!!" >> STDOUT_opt
	exit 1
fi

sed -i -e "s/ run_lapw -ec 0.0001   #/run_lapw -ec $EC_WS -cc $CC_WS -p   #/g" optimize.job
sed -i -e "s/_default/ /g" optimize.job

echo "
Optimization points calculations prepared.
" >> STDOUT_opt

echo ''|./optimize.job >> STDOUT_opt #2>&1

if [ $? -eq 1 ]
	then
	echo "!!! Error in optimize.job execution !!!" >> STDOUT_opt
	exit 1
fi

TIME=`date +%F-%T.%N`

echo "Optimization points have been calculated.
Finish time: $TIME
" >> STDOUT_opt

restore_lapw -f $CASE_WS\_vol____0.00 >> STDOUT_opt #2>&1

if [ $? -eq 1 ]
	then
	echo "!!! Error in restore_lapw !!!" >> STDOUT_opt
	exit 1
fi

TIME=`date +%F-%T.%N`

echo "Vol 0.00 restored.
Finish time: $TIME
" >> STDOUT_opt
