#!/bin/bash

echo "
========================
Running eos_par_abc ...
========================
" >> STDOUT_opt

VOL0=$(awk 'FNR == 21 {print $2}' $CASE_WS.outputeos | bc)
VOL1=$(awk 'FNR == 25 {print $1}' $CASE_WS.outputeos | bc)
A1=$(awk 'FNR == 4 {print $1}' $CASE_WS.struct | bc)
B1=$(awk 'FNR == 4 {print $2}' $CASE_WS.struct | bc)
C1=$(awk 'FNR == 4 {print $3}' $CASE_WS.struct | bc)

A0=$(python -c "print '{:.6f}'.format($A1*($VOL0/$VOL1)**(1./3))")
B0=$(python -c "print '{:.6f}'.format($B1*($VOL0/$VOL1)**(1./3))")
C0=$(python -c "print '{:.6f}'.format($C1*($VOL0/$VOL1)**(1./3))")

echo "Changing cell parameters: a, b, c (triclinic/monoclinic/orthorhombic)
" >> STDOUT_opt
echo "Volume: $VOL1 --> $VOL0" >> STDOUT_opt
echo "a: $A1 --> $A0" >> STDOUT_opt
echo "b: $B1 --> $B0" >> STDOUT_opt
echo "c: $C1 --> $C0" >> STDOUT_opt

sed -i -e "s/$A1/$A0/g" $CASE_WS.struct
sed -i -e "s/$B1/$B0/g" $CASE_WS.struct
sed -i -e "s/$C1/$C0/g" $CASE_WS.struct

TIME=`date +%F-%T.%N`

echo "
STRUCT file has been modified.
Finish time: $TIME
" >> STDOUT_opt
