#!/bin/bash

echo "
========================
Running msr_run ...
========================
" >> STDOUT_opt

echo ''|run_lapw -min -ec $EC_WS -cc $CC_WS -fc $FC_WS -p >> STDOUT_opt #2>&1

if [ $? -eq 1 ]
	then
	echo "!!! Error in run_lapw !!!" >> STDOUT_opt
	exit 1
fi

TIME=`date +%F-%T.%N`

echo "SCF with MSR1a convergence obtained.
Finish time: $TIME
" >> STDOUT_opt

save_lapw -d rkm$RKM_WS\_$KPT_WS\k_$XC_WS\_$STEP_WS\_msr1a >> STDOUT_opt #2>&1

if [ $? -eq 1 ]
	then
	echo "!!! Error in save_lapw !!!" >> STDOUT_opt
	exit 1
fi

echo "MSR1a calculations saved.
" >> STDOUT_opt

