#!/bin/bash

CASE=$1
PRESSURE_CONV=0.01

if [ -e $CASE_WS.outputsgroup ]
	then
	SYMM_GROUP_NO=`grep "Number and name of space group" $CASE_WS.outputsgroup | awk 'FNR == 1 {print $7}'`
	else
	x sgroup >> STDOUT_opt
	SYMM_GROUP_NO=`grep "Number and name of space group" $CASE_WS.outputsgroup | awk 'FNR == 1 {print $7}'`
fi

echo "
Symmetry group: $SYMM_GROUP_NO
" >> STDOUT_opt

if [ "195" -le $SYMM_GROUP_NO && $SYMM_GROUP_NO -le "230" ]
	then
	PRESSURE_0=`awk 'FNR == 28 {print $4}' $CASE_WS.outputeos`

elif [ "75" -le $SYMM_GROUP_NO && $SYMM_GROUP_NO -le "194" ]
	then
	PRESSURE_0=`awk 'FNR == 25 {print $4}' $CASE_WS.outputeos`

elif [ "1" -le $SYMM_GROUP_NO && $SYMM_GROUP_NO -le "74" ]
	then
	PRESSURE_0=`awk 'FNR == 25 {print $4}' $CASE_WS.outputeos`

	else
	echo "Unknown space group.
	" >> STDOUT_opt
	exit 1
fi
