#!/bin/bash

CASE_WS=$1
PRESSURE_CONV='0.01'
PRESSURE_CONVN=`awk "BEGIN {printf \"%.3f\n\", 0 - $PRESSURE_CONV}"`

if [ -e $CASE_WS.outputsgroup ]
	then
	SYMM_GROUP_NO=`grep "Number and name of space group" $CASE_WS.outputsgroup | awk 'FNR == 1 {print $7}'`
	else
	x sgroup >> STDOUT_opt
	SYMM_GROUP_NO=`grep "Number and name of space group" $CASE_WS.outputsgroup | awk 'FNR == 1 {print $7}'`
fi

echo "
Symmetry group: $SYMM_GROUP_NO
" >> STDOUT_opt

if [ "$SYMM_GROUP_NO" -ge "195" -a "$SYMM_GROUP_NO" -le "230" ]
	then
	PRESSURE_0=`awk 'FNR == 28 {print $4}' $CASE_WS.outputeos`

elif [ "$SYMM_GROUP_NO" -ge "75" -a "$SYMM_GROUP_NO" -le "194" ]
	then
	PRESSURE_0=`awk 'FNR == 25 {print $4}' $CASE_WS.outputeos`

elif [ "$SYMM_GROUP_NO" -ge "1" -a "$SYMM_GROUP_NO" -le "74" ]
	then
	PRESSURE_0=`awk 'FNR == 25 {print $4}' $CASE_WS.outputeos`

	else
	echo "Unknown space group. Error in run_full
	" >> STDOUT_opt
	exit 1
fi

# loop

echo "
------> Pressure at point 0.0: $PRESSURE_0
------> Optimized geommetry pressure range: ( $PRESSURE_CONVN to $PRESSURE_CONV )
" >> STDOUT_opt

PRESSURE_CONV=`awk "BEGIN {printf \"%.0f\n\", 1000*$PRESSURE_CONV}"`
PRESSURE_CONVN=`awk "BEGIN {printf \"%.0f\n\", 1000*$PRESSURE_CONVN}"`
PRESSURE_0=`awk "BEGIN {printf \"%.0f\n\", 1000*$PRESSURE_0}"`

while [ "$PRESSURE_0" -ge "$PRESSURE_CONV" -o "$PRESSURE_0" -le "$PRESSURE_CONVN" ]
	do
	
	echo "
	New step." >> STDOUT_opt

	PRESSURE_0=`awk "BEGIN {printf \"%.1f\n\", $PRESSURE_0/2}"`

	PRESSURE_0=`awk "BEGIN {printf \"%.3f\n\", 0.001*$PRESSURE_0}"`
	
	echo "
	------> Pressure at point 0.0: $PRESSURE_0
	" >> STDOUT_opt

	PRESSURE_0=`awk "BEGIN {printf \"%.0f\n\", 1000*$PRESSURE_0}"`

done


PRESSURE_0=`awk "BEGIN {printf \"%.3f\n\", 0.001*$PRESSURE_0}"`
PRESSURE_CONV=`awk "BEGIN {printf \"%.3f\n\", 0.001*$PRESSURE_CONV}"`
PRESSURE_CONVN=`awk "BEGIN {printf \"%.3f\n\", 0.001*$PRESSURE_CONVN}"`

echo "Pressure is converged: $PRESSURE_0 (p_conv = $PRESSURE_CONV).
Optimization finished.
" >> STDOUT_opt
